### PR TITLE
Add --id-prefix parameter to override the default {os}-{arch}- tagId value.

### PR DESCRIPTION
**Pull request by adelton**

### CODE REVIEW

**Comment by tobiasbrunner** [comment]
Wouldn't it make sense to make this a global option (like `--regid`) so it could also be used when retrieving software IDs? I'd expect them to be the same as `tagId` in the SWID tags. The name would have to be changed, though (`--id-prefix` or `--unique-id-prefix`?).

**Comment by adelton** [comment]
I'll try to refresh the pull request this week.

**Comment by adelton** [comment]
Changed the option to `--id-prefix` and made it global, rebased on master -> 89318dfae01d7c95370e68939a1b0a400d9a5264.

**Comment by tobiasbrunner** [comment]
Applied to master. Thanks!

**Pull request closed without merging**
